<Project>
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <AnalysisLevel>10.0</AnalysisLevel>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    </PropertyGroup>
</Project>
