// <auto-generated />
using System;
using BikeLog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BikeLog.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BikeLogDbContext))]
    [Migration("20261002054614_InitialUsageEstimates")]
    partial class InitialUsageEstimates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BikeLog.Domain.Bikes.Bike", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("Kind")
                        .HasColumnType("text");

                    b.Property<string>("Make")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Bikes");
                });

            modelBuilder.Entity("BikeLog.Domain.Components.Component", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long>("InitialUsageEstimateMetres")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Components", null, t =>
                        {
                            t.HasCheckConstraint("CK_Component_InitialUsageEstimate", "\"InitialUsageEstimateMetres\" >= 0");

                            t.HasCheckConstraint("CK_Component_Type", "\"Type\" IN ('Chain', 'Cassette', 'Tyre')");
                        });
                });

            modelBuilder.Entity("BikeLog.Domain.Installations.Installation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BikeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComponentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("OwnerId", "ComponentId");

                    b.HasIndex("OwnerId", "BikeId", "StartUtc");

                    b.ToTable("Installations", null, t =>
                        {
                            t.HasCheckConstraint("CK_Installation_Interval", "\"EndUtc\" IS NULL OR \"EndUtc\" > \"StartUtc\"");

                            t.HasCheckConstraint("CK_Installation_Position", "\"Position\" IN ('Chain', 'Cassette', 'FrontTyre', 'RearTyre')");
                        });
                });

            modelBuilder.Entity("BikeLog.Domain.Maintenance.MaintenanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BikeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ComponentId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Currency")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("PerformedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Task")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasAlternateKey("OwnerId", "Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("OwnerId", "ComponentId");

                    b.HasIndex("OwnerId", "BikeId", "PerformedUtc");

                    b.ToTable("MaintenanceRecords", null, t =>
                        {
                            t.HasCheckConstraint("CK_Maintenance_Cost", "(\"Cost\" IS NULL AND \"Currency\" IS NULL) OR (\"Cost\" IS NOT NULL AND \"Cost\" >= 0 AND \"Currency\" ~ '^[A-Z]{3}$')");
                        });
                });

            modelBuilder.Entity("BikeLog.Domain.Rides.Ride", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BikeId")
                        .HasColumnType("uuid");

                    b.Property<long>("DistanceMetres")
                        .HasColumnType("bigint");

                    b.Property<long?>("DurationSeconds")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasAlternateKey("OwnerId", "Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("OwnerId", "BikeId", "StartUtc");

                    b.ToTable("Rides", null, t =>
                        {
                            t.HasCheckConstraint("CK_Ride_Distance", "\"DistanceMetres\" > 0");

                            t.HasCheckConstraint("CK_Ride_Duration", "\"DurationSeconds\" IS NULL OR \"DurationSeconds\" > 0");
                        });
                });

            modelBuilder.Entity("BikeLog.Infrastructure.Persistence.ComponentUsageRow", b =>
                {
                    b.Property<Guid>("ComponentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CalculatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasUnknownDuration")
                        .HasColumnType("boolean");

                    b.Property<long>("LifetimeMetres")
                        .HasColumnType("bigint");

                    b.Property<long>("LifetimeSeconds")
                        .HasColumnType("bigint");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("ComponentId");

                    b.HasIndex("OwnerId", "ComponentId")
                        .IsUnique();

                    b.ToTable("ComponentUsages");
                });

            modelBuilder.Entity("BikeLog.Infrastructure.Persistence.InstallationUsageRow", b =>
                {
                    b.Property<Guid>("InstallationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CalculatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasUnknownDuration")
                        .HasColumnType("boolean");

                    b.Property<long>("Metres")
                        .HasColumnType("bigint");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<long>("Seconds")
                        .HasColumnType("bigint");

                    b.HasKey("InstallationId");

                    b.HasIndex("OwnerId", "InstallationId")
                        .IsUnique();

                    b.ToTable("InstallationUsages");
                });

            modelBuilder.Entity("BikeLog.Domain.Installations.Installation", b =>
                {
                    b.HasOne("BikeLog.Domain.Bikes.Bike", null)
                        .WithMany()
                        .HasForeignKey("OwnerId", "BikeId")
                        .HasPrincipalKey("OwnerId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BikeLog.Domain.Components.Component", null)
                        .WithMany()
                        .HasForeignKey("OwnerId", "ComponentId")
                        .HasPrincipalKey("OwnerId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BikeLog.Domain.Maintenance.MaintenanceRecord", b =>
                {
                    b.HasOne("BikeLog.Domain.Bikes.Bike", null)
                        .WithMany()
                        .HasForeignKey("OwnerId", "BikeId")
                        .HasPrincipalKey("OwnerId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BikeLog.Domain.Components.Component", null)
                        .WithMany()
                        .HasForeignKey("OwnerId", "ComponentId")
                        .HasPrincipalKey("OwnerId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BikeLog.Domain.Rides.Ride", b =>
                {
                    b.HasOne("BikeLog.Domain.Bikes.Bike", null)
                        .WithMany()
                        .HasForeignKey("OwnerId", "BikeId")
                        .HasPrincipalKey("OwnerId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BikeLog.Infrastructure.Persistence.ComponentUsageRow", b =>
                {
                    b.HasOne("BikeLog.Domain.Components.Component", null)
                        .WithOne()
                        .HasForeignKey("BikeLog.Infrastructure.Persistence.ComponentUsageRow", "OwnerId", "ComponentId")
                        .HasPrincipalKey("BikeLog.Domain.Components.Component", "OwnerId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BikeLog.Infrastructure.Persistence.InstallationUsageRow", b =>
                {
                    b.HasOne("BikeLog.Domain.Installations.Installation", null)
                        .WithOne()
                        .HasForeignKey("BikeLog.Infrastructure.Persistence.InstallationUsageRow", "OwnerId", "InstallationId")
                        .HasPrincipalKey("BikeLog.Domain.Installations.Installation", "OwnerId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
